services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      # - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  carperntry-shop:
      container_name: carperntry-shop
      image: ghcr.io/simanga-dev/carperntry-shop:latest
      labels:
        - "traefik.http.routers.carpentry.rule=Host(`carperntry.simanga.dev`)"
        - "traefik.http.services.carpentry.loadbalancer.server.port=8080"
      restart: always
      environment:
        - DB_CONNECTION=Host=postgres-db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB}
      depends_on:
        - postgres-db
  # meilisearch:
  #     container_name: search-meilisearch
  #     image: getmeili/meilisearch:v1.7.3
  #     restart: always
  #     ports:
  #       - "7700:7700"
  #     # user: "${UID}:${GID}"
  #     environment:
  #       # - MEILI_HOST=http://meilisearch:7700
  #       - MEILI_NO_ANALYTICS=true
  #     volumes:
  #       - ./meili_data_v1.7:/meili_data
  #
  postgres-db:
    image: postgres
    # ports:
    #   # - "5432:5432"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
