services:
  carperntry-shop:
      container_name: carperntry-shop
      image: ghcr.io/simanga-dev/carperntry-shop:latest
      restart: always
      ports:
        - "8080:8080"
      environment:
        - DB_CONNECTION=Host=postgres-db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB}
      depends_on:
        - postgres-db
  # meilisearch:
  #     container_name: search-meilisearch
  #     image: getmeili/meilisearch:v1.7.3
  #     restart: always
  #     ports:
  #       - "7700:7700"
  #     # user: "${UID}:${GID}"
  #     environment:
  #       # - MEILI_HOST=http://meilisearch:7700
  #       - MEILI_NO_ANALYTICS=true
  #     volumes:
  #       - ./meili_data_v1.7:/meili_data
  #
  postgres-db:
    image: postgres
    # ports:
    #   # - "5432:5432"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
